receivers:
  # Receive telemetry data via OTLP protocol
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:3000  # Frontend
            - http://frontend:3000
            - "*"
  
  # Receive Jaeger traces (if needed for compatibility)
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832

  # Receive Zipkin traces (if needed for compatibility)
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  # Basic processing for traces
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Add resource attributes
  resource:
    attributes:
      - key: environment
        value: ${ENVIRONMENT:-development}
        action: upsert
      - key: service.namespace
        value: brain_net
        action: upsert

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 500
    spike_limit_mib: 100
    check_interval: 5s

exporters:
  # Export traces to Jaeger
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: brain_net
    const_labels:
      environment: ${ENVIRONMENT:-development}

  # Export logs to stdout for debugging
  logging:
    loglevel: info

  # Optional: Export to OTLP endpoint for other backends
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [memory_limiter, resource, batch]
      exporters: [jaeger, logging]
    
    # Metrics pipeline  
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]
    
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [logging]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888 